### ISSUE TITLE
Move EditProduct Component to Admin Folder

### ISSUE THREAD

**Issue by katmccrum** [Sassy-Software-Engineers/Grace-Shopper#116]
Move edit product component from Product into Admin and build out the Admin dashboard from wireframes

**Comment by dcbasham** [comment]
Moved it into the correct folder already,  starting to work on it now to make sure it is looking like the wireframes.

**Comment by dcbasham** [comment]
Making a new Issue for the Admin Dashboard Component to Edit/Delete/Add Products and View/Edit Users.
