### ISSUE TITLE
Unauthenticated Users - Checkout

### ISSUE THREAD

**Issue by katmccrum** [Sassy-Software-Engineers/Grace-Shopper#7]
I want to purchase items in the cart, so that I can get the items I want
I can specify a shipping address and email address when I checkout, so that the items can arrive at the right place

Implementation: implement a front-end form (requiring specified info) that sends a request to the back-end to confirm the order and update inventory.

**Comment by katmccrum** [comment]
I should receive a confirmation email after I checkout, so that I know my order is being looked at.

Implementation:

**Comment by katmccrum** [comment]
I should receive a notification email when the order ships, and then when the order is delivered, so that I can stay up to date on when my order will arrive.

Implementation:

**Comment by noellehuchette** [comment]
I should be able to look up orders by order number to view current status.

Implementation: implement a back-end route that serves up order details based on an order number provided in a form that directs to an order details page.
