### ISSUE TITLE
Cart LocalStorage/anonymous user

### ISSUE THREAD

**Issue by dcbasham** [Sassy-Software-Engineers/Grace-Shopper#96]
A user can refresh the page and have the cart persist, so that I don't lose my work (you may use sessionStorage, localStorage, cookies or JWT for this).
I should be be able to create an account/login to an existing account and continue editing that same cart so that I don't lose any progress I made before I logged in.

Implementation: carts should be stored locally in the browser, taking priority over existing saved carts

**Comment by katmccrum** [comment]
- anonymous user route:

- if a person is not logged in, when they "add to cart" , will register the cart to an anonymous user 
- once they sign in, will either create new user with inputted username and PW or match to existing user
